ALTER TABLE tasks ADD COLUMN retry_count INT NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN execution_started_at TIMESTAMPTZ;
ALTER TABLE tasks ADD COLUMN block_reason TEXT NOT NULL DEFAULT '';

ALTER TABLE projects ADD COLUMN max_task_retry_count INT NOT NULL DEFAULT 5;
ALTER TABLE projects ADD COLUMN max_execution_minutes INT NOT NULL DEFAULT 120;
ALTER TABLE projects ADD COLUMN max_event_count INT NOT NULL DEFAULT 20000;
ALTER TABLE projects ADD COLUMN cost_budget DOUBLE PRECISION;
