ALTER TABLE projects ADD COLUMN IF NOT EXISTS smart_routing BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE token_usage ADD COLUMN IF NOT EXISTS cache_read_tokens INT NOT NULL DEFAULT 0;
ALTER TABLE token_usage ADD COLUMN IF NOT EXISTS cache_write_tokens INT NOT NULL DEFAULT 0;
