export const DEFAULT_FLEET = [
  {
    name: "AI Planner",
    role: "planner",
    goal: "Break requirements into execution plans, milestones, and task dependencies.",
    model_level_group: "balanced",
    autonomy_level: "supervised",
    assignment_strategy: "auto_join",
  },
  {
    name: "AI Backend Developer",
    role: "backend",
    goal: "Implement server-side features, persistence, APIs, and integration logic.",
    model_level_group: "balanced",
    autonomy_level: "supervised",
    assignment_strategy: "auto_join",
  },
  {
    name: "AI Frontend Developer",
    role: "frontend",
    goal: "Build user-facing flows, application state, and responsive interface behavior.",
    model_level_group: "balanced",
    autonomy_level: "supervised",
    assignment_strategy: "auto_join",
  },
  {
    name: "AI Reviewer",
    role: "reviewer",
    goal: "Review changes for correctness, regressions, security issues, and missing tests.",
    model_level_group: "fast",
    autonomy_level: "approval_required",
    assignment_strategy: "auto_join",
  },
  {
    name: "AI QA Tester",
    role: "qa",
    goal: "Design and run verification checks for functional and regression coverage.",
    model_level_group: "fast",
    autonomy_level: "supervised",
    assignment_strategy: "auto_join",
  },
  {
    name: "AI Security Auditor",
    role: "security-auditor",
    goal: "Scan for vulnerabilities and verify secret safety.",
    model_level_group: "fast",
    autonomy_level: "approval_required",
    assignment_strategy: "auto_join",
  },
  {
    name: "AI DB Architect",
    role: "db-architect",
    goal: "Design schemas, create migrations, and optimize queries.",
    model_level_group: "balanced",
    autonomy_level: "supervised",
    assignment_strategy: "auto_join",
  },
  {
    name: "AI Documentation Writer",
    role: "documentation-writer",
    goal: "Write and update high-quality project documentation, readme files, and user guides.",
    model_level_group: "balanced",
    autonomy_level: "supervised",
    assignment_strategy: "auto_join",
  },
];
