import { FormEvent, useEffect, useRef, useState } from "react";
import { CheckCircle2, ChevronDown, KeyRound, Loader2, Plus, Terminal as TerminalIcon, X } from "lucide-react";
import { PROVIDERS } from "@/lib/model-options";
import { generatedCredentialLabel } from "./AddApiCredentialModal";
import { CliAuthFlow } from "./CliAuthFlow";

type FormState = {
  provider: string;
  label: string;
  apiKey: string;
  baseURL: string;
  priority: string;
};

interface AddCliCredentialModalProps {
  form: FormState;
  formError: string;
  isSubmitting: boolean;
  saveState: "idle" | "saved";
  token: string;
  orgID: string;
  onClose: () => void;
  onSubmit: (event: FormEvent<HTMLFormElement>) => void;
  onSetForm: React.Dispatch<React.SetStateAction<FormState>>;
}

export function AddCliCredentialModal({
  form,
  formError,
  isSubmitting,
  saveState,
  token,
  orgID,
  onClose,
  onSubmit,
  onSetForm,
}: AddCliCredentialModalProps) {
  const formRef = useRef<HTMLFormElement>(null);
  const [showTerminal, setShowTerminal] = useState(false);
  const [terminalError, setTerminalError] = useState("");
  const [autoSubmit, setAutoSubmit] = useState(false);

  useEffect(() => {
    if (autoSubmit && form.apiKey) {
      formRef.current?.requestSubmit();
      setAutoSubmit(false);
    }
  }, [autoSubmit, form.apiKey]);

  function openTerminal() {
    if (!orgID || !token) return;
    setTerminalError("");
    setShowTerminal(true);
  }

  useEffect(() => {
    function handleKeyDown(event: KeyboardEvent) {
      if (event.key === "Escape" && !isSubmitting) {
        onClose();
      }
    }
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [onClose, isSubmitting]);

  return (
    <div
      className="fixed inset-0 z-modal grid place-items-center bg-black/45 px-4 py-6 backdrop-blur-sm"
      role="dialog"
      aria-modal="true"
      aria-labelledby="add-credential-title"
      onMouseDown={onClose}
    >
      <div
        className="glass-panel animate-modal-in w-full max-w-2xl max-h-[90vh] overflow-y-auto rounded-lg p-5 shadow-2xl"
        onMouseDown={(event) => event.stopPropagation()}
      >
        <div className="mb-4 flex items-center justify-between">
          <h3 id="add-credential-title" className="flex items-center gap-2 font-semibold text-foreground">
            <Plus size={18} className="text-brand-primary" />
            Add CLI Auth Profile
          </h3>
          <button
            type="button"
            onClick={onClose}
            disabled={isSubmitting}
            className="rounded p-1.5 text-content-muted transition-colors hover:bg-surface hover:text-foreground disabled:cursor-not-allowed disabled:opacity-50"
            title="Close"
          >
            <X size={16} />
          </button>
        </div>

        {formError && (
          <div className="mb-4 rounded-md border border-red-500/25 bg-red-500/10 p-3 text-xs font-medium text-red-600 dark:text-red-300">
            {formError}
          </div>
        )}

        <form ref={formRef} onSubmit={onSubmit} className="space-y-4">
          <label className="flex flex-col gap-1.5">
            <span className="text-xs font-semibold uppercase tracking-wider text-content-muted">Provider</span>
            <div className="relative">
              <select
                value={form.provider}
                onChange={(event) => {
                  const provider = event.target.value;
                  onSetForm((prev) => {
                    const currentGen = generatedCredentialLabel(prev.provider, prev.apiKey);
                    const isAutogenerated = !prev.label.trim() || prev.label === currentGen || prev.label === `${prev.provider} key`;
                    return {
                      ...prev,
                      provider,
                      label: isAutogenerated ? generatedCredentialLabel(provider, prev.apiKey) : prev.label,
                    };
                  });
                }}
                className="w-full appearance-none rounded-md border border-stroke bg-background pl-3 pr-10 py-2 text-sm text-foreground transition-all duration-150 focus:border-brand-primary focus:outline-none focus:ring-2 focus:ring-brand-primary/20"
              >
                <optgroup label="CLI Tools">
                  {PROVIDERS.filter((p) => p !== "gateway" && p.startsWith("cli:")).map((provider) => (
                    <option key={provider} value={provider}>
                      {provider}
                    </option>
                  ))}
                </optgroup>
              </select>
              <ChevronDown className="absolute right-3 top-3 text-content-muted pointer-events-none" size={14} />
            </div>
          </label>

          <label className="flex flex-col gap-1.5">
            <span className="text-xs font-semibold uppercase tracking-wider text-content-muted">Label</span>
            <input
              value={form.label}
              onChange={(event) => onSetForm((prev) => ({ ...prev, label: event.target.value }))}
              placeholder="primary, backup, team-api"
              className="rounded-md border border-stroke bg-background px-3 py-2 text-sm text-foreground transition-all duration-150 focus:border-brand-primary focus:outline-none focus:ring-2 focus:ring-brand-primary/20"
            />
          </label>

          <label className="flex flex-col gap-1.5">
            <span className="text-xs font-semibold uppercase tracking-wider text-content-muted">CLI Session Configuration</span>
            {!showTerminal && (
              <div className="mb-2">
                <button
                  type="button"
                  onClick={openTerminal}
                  className="w-full inline-flex items-center justify-center gap-2 rounded-md border border-brand-primary/30 bg-brand-primary/10 px-4 py-4 text-sm font-semibold text-brand-primary transition hover:bg-brand-primary/20"
                >
                  <TerminalIcon size={18} />
                  Launch Interactive Login Terminal
                </button>
                {terminalError && <p className="text-red-500 text-xs mt-1">{terminalError}</p>}
              </div>
            )}

            {showTerminal && orgID && token && (
              <div className="mb-2">
                <CliAuthFlow
                  provider={form.provider}
                  orgID={orgID}
                  token={token}
                  onExit={(payload) => {
                    onSetForm((prev) => ({ ...prev, apiKey: JSON.stringify(payload, null, 2) }));
                    setShowTerminal(false);
                    setAutoSubmit(true);
                  }}
                  onError={(err) => setTerminalError(err)}
                />

                {terminalError && <p className="text-red-500 text-xs mt-1">{terminalError}</p>}
                <button
                  type="button"
                  onClick={() => setShowTerminal(false)}
                  className="mt-2 text-xs text-content-muted hover:text-foreground underline"
                >
                  Close Terminal (Cancel)
                </button>
              </div>
            )}

            <div className="mt-2 border-t border-stroke pt-3">
              <span className="text-xs font-semibold uppercase tracking-wider text-content-muted block mb-2">Or Provide JSON Manually</span>
              <div className="relative">
                <KeyRound className="absolute left-3 top-2.5 text-content-muted" size={14} />
                <textarea
                  value={form.apiKey}
                  onChange={(event) => {
                    const key = event.target.value;
                    onSetForm((prev) => ({ ...prev, apiKey: key }));
                  }}
                  placeholder={'{\n  "token": "..."\n}'}
                  rows={4}
                  className="w-full rounded-md border border-stroke bg-background py-2 pl-9 pr-3 text-xs font-mono text-foreground transition-all duration-150 focus:border-brand-primary focus:outline-none focus:ring-2 focus:ring-brand-primary/20 resize-none"
                />
              </div>
            </div>
          </label>

          <label className="flex flex-col gap-1.5">
            <div className="flex items-center justify-between gap-3">
              <span className="text-xs font-semibold uppercase tracking-wider text-content-muted">Priority</span>
              <span className="text-right text-[10px] font-medium text-content-muted">Lower = runs first (0 = highest)</span>
            </div>
            <input
              type="number"
              value={form.priority}
              onChange={(event) => onSetForm((prev) => ({ ...prev, priority: event.target.value }))}
              className="rounded-md border border-stroke bg-background px-3 py-2 text-sm text-foreground transition-all duration-150 focus:border-brand-primary focus:outline-none focus:ring-2 focus:ring-brand-primary/20"
            />
          </label>

          <div className="flex justify-end gap-2 pt-1">
            <button
              type="button"
              onClick={onClose}
              disabled={isSubmitting}
              className="rounded-md border border-stroke px-4 py-2.5 text-sm font-semibold text-foreground transition hover:bg-surface disabled:cursor-not-allowed disabled:opacity-50"
            >
              Cancel
            </button>
            <button
              disabled={isSubmitting || !token || !orgID || !form.apiKey.trim()}
              className="inline-flex min-w-32 items-center justify-center gap-2 rounded-md bg-brand-primary px-4 py-2.5 text-sm font-semibold text-white transition hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-50"
              type="submit"
            >
              {isSubmitting && <Loader2 size={14} className="animate-spin" />}
              {saveState === "saved" && !isSubmitting ? (
                <>
                  <CheckCircle2 size={14} />
                  Saved
                </>
              ) : (
                "Save"
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
