package steps

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/auto-code-os/auto-code-os/server/internal/workflow"
	"github.com/auto-code-os/auto-code-os/server/pkg/models"
)

// PlanStep implements Step for the execution planning phase.
// It acts as a deterministic orchestration checkpoint that reads the OpenSpec
// generated by Analyze and prepares structured subtask assignments for Code agents.
// No LLM call is made — this step is pure logic.
type PlanStep struct {
	rt        StepRuntime
	tasks     TaskReader
	worktree  WorktreeManager
	workspace WorkspaceLoader
	status    StatusUpdater
	log       Logger
}

func NewPlanStep(
	rt StepRuntime,
	tasks TaskReader,
	_ LLMRunner, // preserved for API compatibility; unused
	worktree WorktreeManager,
	workspace WorkspaceLoader,
	status StatusUpdater,
	log Logger,
) *PlanStep {
	return &PlanStep{
		rt:        rt,
		tasks:     tasks,
		worktree:  worktree,
		workspace: workspace,
		status:    status,
		log:       log,
	}
}

func (s *PlanStep) ID() string                         { return workflow.StepPlan }
func (s *PlanStep) StatusOnResume(_ StepResult) string { return models.TaskStatusCoding }

func (s *PlanStep) Execute(ctx context.Context, stepCtx workflow.StepContext) (StepResult, error) {
	t, err := s.tasks.GetByID(ctx, s.rt.Task.ID)
	if err == nil && t.Complexity == models.TaskComplexityEasy {
		return StepResult{"status": "skipped", "info": "skipped plan step for easy task"}, nil
	}

	// Phase 1+2: Parse OpenSpec from task analysis
	var analysis models.TaskAnalysis
	if t != nil && len(t.Analysis) > 0 {
		_ = json.Unmarshal(t.Analysis, &analysis)
	}

	s.log.Log(ctx, s.rt.Task.ID, &s.rt.JobID, "info", "Plan: parsing tasks_md into structured subtask list")
	subtasks := workflow.ParseTasksMD(analysis.TasksMD)
	s.log.Log(ctx, s.rt.Task.ID, &s.rt.JobID, "info", fmt.Sprintf("Plan: found %d backend subtasks, %d frontend subtasks", len(subtasks["backend"]), len(subtasks["frontend"])))

	// Phase 3: Decide whether to skip frontend
	skipFE := shouldSkipFrontend(analysis, subtasks)
	s.log.Log(ctx, s.rt.Task.ID, &s.rt.JobID, "info", fmt.Sprintf("Plan: skip_frontend=%v (category=%s)", skipFE, analysis.PrimaryCategory))

	// Build output
	out := StepResult{
		"subtasks":       subtasks,
		"skip_frontend":  skipFE,
		"execution_plan": analysis.ExecutionPlan,
	}

	// Setup branches (preserved from original)
	s.log.Log(ctx, s.rt.Task.ID, &s.rt.JobID, "info", "Plan: setting up role branches")
	if s.worktree != nil {
		targetRepos, errRepos := s.worktree.LoadTargetRepositories(ctx, s.rt.Task)
		if errRepos == nil && len(targetRepos) > 0 {
			integrationBranch := fmt.Sprintf("feature/%s", s.rt.Task.ID)
			beBranch := fmt.Sprintf("feature/%s-be", s.rt.Task.ID)
			feBranch := fmt.Sprintf("feature/%s-fe", s.rt.Task.ID)

			var ws *models.TaskWorkspace
			if s.workspace != nil {
				ws, _ = s.workspace.LoadTaskWorkspace(ctx, s.rt.Task)
			}
			s.worktree.SetupRoleBranches(ctx, s.rt.Task, s.rt.Agent, s.rt.JobID, targetRepos, ws, skipFE)
			branchesMap := map[string]string{
				"integration": integrationBranch,
				"backend":     beBranch,
			}
			if !skipFE {
				branchesMap["frontend"] = feBranch
			}
			out["branches"] = branchesMap
		}
	}

	if s.status != nil {
		if _, err := s.status.UpdateTaskStatus(ctx, s.rt.Task.ID, models.TaskStatusCoding); err != nil {
			return nil, err
		}
	}
	s.log.Log(ctx, s.rt.Task.ID, &s.rt.JobID, "info", "Plan: orchestration checkpoint complete")
	return out, nil
}

// parseTasksMD extracts structured subtasks from the tasks_md markdown generated
// by the Analyze step. It classifies each heading group as "backend" or "frontend"
// based on keyword matching, then collects checkbox items under each group.
//
// Input format (from OpenSpec):
//
//	## 1. Backend API
//	- [ ] 1.1 Create API endpoint
//	- [ ] 1.2 Add validation
//	## 2. Frontend Components
//	- [ ] 2.1 Build form component
//
// Output: map[string][]string{
//
//	"backend":  ["1.1 Create API endpoint", "1.2 Add validation"],
//	"frontend": ["2.1 Build form component"],
//
// }

// shouldSkipFrontend determines whether the frontend coding step should be skipped
// based on the task analysis and parsed subtask breakdown.
func shouldSkipFrontend(analysis models.TaskAnalysis, subtasks map[string][]string) bool {
	// 1. If any affected files are frontend files, do NOT skip (file-path signal overrides category hint)
	for _, file := range analysis.AffectedFiles {
		if isFrontendFile(file) {
			return false
		}
	}

	// 2. If frontend subtasks exist, keep the frontend step enabled even if the
	// category hint leans backend.
	if len(subtasks["frontend"]) > 0 {
		return false
	}

	// 3. Fallback: if category is backend/database/devops/security/documentation, skip
	switch strings.ToLower(analysis.PrimaryCategory) {
	case "backend", "database", "devops", "security", "documentation":
		return true
	}

	// 4. Default: no frontend file signal, no frontend subtasks, and no explicit
	// non-frontend category hint. Skip the frontend step.
	return true
}
