package steps

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/auto-code-os/auto-code-os/server/internal/policy"
	"github.com/auto-code-os/auto-code-os/server/internal/workflow"
	"github.com/auto-code-os/auto-code-os/server/pkg/models"
)

type WorkflowCheckpointRepo interface {
	DeleteCheckpoints(ctx context.Context, taskID string, steps []string) error
}

// PlanStep implements Step for the execution planning phase.
// It acts as a deterministic orchestration checkpoint that reads the OpenSpec
// generated by Analyze and prepares structured subtask assignments for Code agents.
// No LLM call is made — this step is pure logic.
type PlanStep struct {
	rt        StepRuntime
	tasks     TaskRepository
	worktree  WorktreeManager
	workspace WorkspaceLoader
	status    StatusUpdater
	log       Logger
	workflows WorkflowCheckpointRepo
	maxCost   float64
}

func NewPlanStep(
	rt StepRuntime,
	tasks TaskRepository,
	_ LLMRunner, // preserved for API compatibility; unused
	worktree WorktreeManager,
	workspace WorkspaceLoader,
	status StatusUpdater,
	log Logger,
	workflows WorkflowCheckpointRepo,
	maxCost float64,
) *PlanStep {
	return &PlanStep{
		rt:        rt,
		tasks:     tasks,
		worktree:  worktree,
		workspace: workspace,
		status:    status,
		log:       log,
		workflows: workflows,
		maxCost:   maxCost,
	}
}

func (s *PlanStep) ID() string                         { return workflow.StepPlan }
func (s *PlanStep) StatusOnResume(_ StepResult) string { return models.TaskStatusCoding }

func classifyHeadingLocal(heading string) string {
	lower := strings.ToLower(heading)
	frontendSignals := []string{"frontend", "ui", "component", "page", "view", "style", "css", "layout", "giao diện", "giao dien"}
	for _, signal := range frontendSignals {
		if strings.Contains(lower, signal) {
			return "frontend"
		}
	}
	return "backend"
}

// executionIROperationKeywords infers an ExecutionIR operation from a unit's
// objective/task text. Checked in order; first match wins. ExecutionUnit
// carries no explicit CRUD verb, so this is a best-effort heuristic — default
// is "modify" since most units touch existing code.
var executionIROperationKeywords = []struct {
	keyword   string
	operation string
}{
	{"delete", "delete"},
	{"remove", "delete"},
	{"refactor", "refactor"},
	{"migrate", "refactor"},
	{"create", "create"},
	{"add", "create"},
	{"implement", "create"},
}

func inferExecutionIROperation(unit models.ExecutionUnit) string {
	text := strings.ToLower(unit.Objective + " " + strings.Join(unit.Tasks, " "))
	for _, kw := range executionIROperationKeywords {
		if strings.Contains(text, kw.keyword) {
			return kw.operation
		}
	}
	return "modify"
}

// executionIRBudgetForUnit derives phase budgets from a unit's declared file
// scope: wider units get more discovery/implementation room. Validation stays
// fixed since it only re-runs targeted tests, not full exploration.
func executionIRBudgetForUnit(unit models.ExecutionUnit) models.PhaseBudgets {
	maxFiles := unit.Constraints.MaxFiles
	if maxFiles <= 0 {
		maxFiles = 1
	}
	implementation := maxFiles * 3
	if implementation < 6 {
		implementation = 6
	} else if implementation > 24 {
		implementation = 24
	}
	discovery := maxFiles + 2
	if discovery > 8 {
		discovery = 8
	}
	return models.PhaseBudgets{Discovery: discovery, Implementation: implementation, Validation: 3}
}

// stringifyAcceptanceCriterion renders a free-form LLM acceptance-criterion
// map as a single string. AcceptanceCriteria has no fixed schema (see
// analyze_parser.go), so common candidate keys are tried before falling back
// to the raw JSON so no data is silently dropped.
func stringifyAcceptanceCriterion(m map[string]any) string {
	for _, key := range []string{"criterion", "description", "text", "title"} {
		if s, ok := m[key].(string); ok && s != "" {
			return s
		}
	}
	raw, _ := json.Marshal(m)
	return string(raw)
}

// BuildExecutionIRs deterministically derives one ExecutionIR per
// ExecutionUnit when the Planner hasn't already emitted them directly. This
// mirrors MapLegacyPhasesToUnits: a pure mapping step, no LLM call, so
// downstream state-machine execution always has a validated IR to compile
// prompts from (REQ-001).
func BuildExecutionIRs(analysis *models.TaskAnalysis) {
	if len(analysis.ExecutionIRs) > 0 {
		return
	}
	acceptance := make([]string, 0, len(analysis.AcceptanceCriteria))
	for _, c := range analysis.AcceptanceCriteria {
		acceptance = append(acceptance, stringifyAcceptanceCriterion(c))
	}

	for _, unit := range analysis.ExecutionUnits {
		constraints := unit.Tasks
		if constraints == nil {
			constraints = []string{}
		}
		ir := models.ExecutionIR{
			SchemaVersion: models.CurrentExecutionIRSchemaVersion,
			NodeID:        unit.ID,
			Intent: models.Intent{
				Capability: unit.Objective,
				Operation:  inferExecutionIROperation(unit),
			},
			Constraints: constraints,
			Acceptance:  acceptance,
			Budget:      executionIRBudgetForUnit(unit),
		}
		if err := models.ValidateExecutionIR(ir); err != nil {
			// A derivation bug should not silently corrupt FrozenContext;
			// skip the malformed IR rather than propagate it downstream.
			continue
		}
		analysis.ExecutionIRs = append(analysis.ExecutionIRs, ir)
	}
}

func MapLegacyPhasesToUnits(analysis *models.TaskAnalysis) {
	if len(analysis.ExecutionUnits) > 0 {
		return
	}
	for i, phase := range analysis.ExecutionPhases {
		unit := models.ExecutionUnit{
			ID:        fmt.Sprintf("phase_%d", i),
			Objective: phase.Phase,
			Tasks:     phase.Tasks,
			ExecutionProfile: models.ExecutionProfile{
				Agent:  classifyHeadingLocal(phase.Phase),
				Skills: []string{},
			},
			Constraints: models.ExecutionConstraints{
				Parallelizable:  false,
				MaxFiles:        4,
				EstimatedTokens: 6000,
				MaxRisk:         "low",
			},
		}
		if i > 0 {
			unit.Dependencies = []string{fmt.Sprintf("phase_%d", i-1)}
		}
		analysis.ExecutionUnits = append(analysis.ExecutionUnits, unit)
	}
}

func (s *PlanStep) Execute(ctx context.Context, stepCtx workflow.StepContext) (StepResult, error) {
	t, err := s.tasks.GetByID(ctx, s.rt.Task.ID)
	if err == nil && t.Complexity == models.TaskComplexityEasy {
		return StepResult{"status": "skipped", "info": "skipped plan step for easy task"}, nil
	}

	// Phase 1+2: Parse OpenSpec from task analysis
	var analysis models.TaskAnalysis
	if t != nil && len(t.Analysis) > 0 {
		_ = json.Unmarshal(t.Analysis, &analysis)
	}

	// Check if Analyze output already contains execution_units with dependencies and tasks
	hasUnits := len(analysis.ExecutionUnits) > 0
	if hasUnits {
		for _, u := range analysis.ExecutionUnits {
			if len(u.Tasks) == 0 {
				hasUnits = false
				break
			}
		}
	}

	if hasUnits {
		s.log.Log(ctx, s.rt.Task.ID, &s.rt.JobID, "info", "Plan step skipped — execution units already provided by analyze step")
	} else {
		// Backward Compatibility: Map legacy phases to units
		MapLegacyPhasesToUnits(&analysis)
	}

	// Derive Execution IRs (REQ-001) when the Planner hasn't emitted them directly.
	BuildExecutionIRs(&analysis)

	targets, dropped, resolveErr := ResolveExecutionIRTargets(analysis)
	analysis.ExecutionIRTargets = targets
	for nodeID, dropList := range dropped {
		if len(dropList) > 0 {
			s.log.Log(ctx, s.rt.Task.ID, &s.rt.JobID, "warn", fmt.Sprintf("Plan: node %s — LLM-suggested paths not corroborated by AffectedFiles: %v", nodeID, dropList))
		}
	}
	if resolveErr != nil {
		if models.IsStateMachineEnabled(ctx) {
			s.log.Log(ctx, s.rt.Task.ID, &s.rt.JobID, "error", fmt.Sprintf("Plan intent resolution failed: %v", resolveErr))
			specStatus := "paused"
			_, _ = s.tasks.Update(ctx, s.rt.Task.ID, models.UpdateTaskInput{
				SpecStatus: &specStatus,
			})
			if s.status != nil {
				_, _ = s.status.UpdateTaskStatus(ctx, s.rt.Task.ID, models.TaskStatusSpecReview)
			}
			return nil, fmt.Errorf("intent resolution failed: %w", resolveErr)
		}
		s.log.Log(ctx, s.rt.Task.ID, &s.rt.JobID, "warn", fmt.Sprintf("Plan: intent resolution incomplete: %v", resolveErr))
	}

	// Validate ExecutionUnits DAG
	maxCostThreshold := s.maxCost
	if maxCostThreshold <= 0 {
		maxCostThreshold = 8.0 // default
	}

	// Dynamic Scheduler Policy validation
	if errVal := policy.ValidateDAG(analysis.ExecutionUnits, maxCostThreshold); errVal != nil {
		s.log.Log(ctx, s.rt.Task.ID, &s.rt.JobID, "warn", fmt.Sprintf("Plan validation failed: %v", errVal))

		// Auto-split retry logic (up to 2 times)
		if analysis.RetryCount < 2 {
			analysis.RetryCount++
			s.log.Log(ctx, s.rt.Task.ID, &s.rt.JobID, "info", fmt.Sprintf("Retrying Analyze step (Attempt %d/2) due to validation failure...", analysis.RetryCount))

			// 1. Update retry count and reset spec status in DB
			rawAnalysis, marshalErr := json.Marshal(analysis)
			if marshalErr == nil {
				emptyStatus := ""
				_, _ = s.tasks.Update(ctx, s.rt.Task.ID, models.UpdateTaskInput{
					Analysis:   rawAnalysis,
					SpecStatus: &emptyStatus,
				})
				s.rt.Task.Analysis = rawAnalysis
				s.rt.Task.SpecStatus = emptyStatus
			}

			// 2. Clear checkpoints for analyze and plan so they re-execute
			if s.workflows != nil {
				_ = s.workflows.DeleteCheckpoints(ctx, s.rt.Task.ID, []string{"analyze", "plan"})
			}

			// 3. Return ErrGraphChanged to trigger re-running of analyze
			return nil, workflow.ErrGraphChanged
		}

		// If exceeded 2 retries, pause the workflow and ask for Human Review
		s.log.Log(ctx, s.rt.Task.ID, &s.rt.JobID, "error", "Validation failed 2 times. Pausing workflow for Human Review.")

		specStatus := "paused"
		_, _ = s.tasks.Update(ctx, s.rt.Task.ID, models.UpdateTaskInput{
			SpecStatus: &specStatus,
		})
		if s.status != nil {
			_, _ = s.status.UpdateTaskStatus(ctx, s.rt.Task.ID, models.TaskStatusSpecReview)
		}

		return nil, fmt.Errorf("%w: %v", workflow.ErrPaused, errVal)
	}

	s.log.Log(ctx, s.rt.Task.ID, &s.rt.JobID, "info", "Plan: mapping ExecutionUnits into structured subtask list")
	subtasks := make(map[string][]string)
	for _, unit := range analysis.ExecutionUnits {
		agent := strings.ToLower(unit.ExecutionProfile.Agent)
		if agent == "" {
			agent = "backend" // default
		}
		var sb strings.Builder
		sb.WriteString(fmt.Sprintf("## %s\n", unit.Objective))
		for _, taskStr := range unit.Tasks {
			sb.WriteString(fmt.Sprintf("- [ ] %s\n", taskStr))
		}
		subtasks[agent] = append(subtasks[agent], sb.String())
	}
	s.log.Log(ctx, s.rt.Task.ID, &s.rt.JobID, "info", fmt.Sprintf("Plan: mapped %d backend units, %d frontend units", len(subtasks["backend"]), len(subtasks["frontend"])))

	// Phase 3: Decide whether to skip frontend
	skipFE := shouldSkipFrontend(analysis, subtasks)
	s.log.Log(ctx, s.rt.Task.ID, &s.rt.JobID, "info", fmt.Sprintf("Plan: skip_frontend=%v (category=%s)", skipFE, analysis.PrimaryCategory))

	// Phase 4: Create FrozenContext snapshot — immutable execution contract
	frozen := models.FrozenContext{
		SpecHash:            analysis.SpecHash,
		ProposalMD:          analysis.ProposalMD,
		SpecsMD:             analysis.SpecsMD,
		DesignMD:            analysis.DesignMD,
		TasksMD:             analysis.TasksMD,
		ExecutionUnits:      analysis.ExecutionUnits,
		ExecutionIRs:        analysis.ExecutionIRs,
		ExecutionIRTargets:  analysis.ExecutionIRTargets,
		ExecutionBoundaries: analysis.ExecutionBoundaries,
		AffectedFiles:       analysis.AffectedFiles,
		AcceptanceCriteria:  analysis.AcceptanceCriteria,
		ExecutionPhases:     analysis.ExecutionPhases,
		Risks:               analysis.Risks,
		RiskDomains:         analysis.RiskDomains,
	}
	frozenJSON, _ := json.Marshal(frozen)
	s.log.Log(ctx, s.rt.Task.ID, &s.rt.JobID, "info", "Plan: created FrozenContext snapshot")

	// Build output
	out := StepResult{
		"subtasks":         subtasks,
		"skip_frontend":    skipFE,
		"execution_phases": analysis.ExecutionPhases,
		"frozen_context":   string(frozenJSON),
	}

	// Setup branches (preserved from original)
	s.log.Log(ctx, s.rt.Task.ID, &s.rt.JobID, "info", "Plan: setting up role branches")
	if s.worktree != nil {
		targetRepos, errRepos := s.worktree.LoadTargetRepositories(ctx, s.rt.Task)
		if errRepos == nil && len(targetRepos) > 0 {
			integrationBranch := fmt.Sprintf("feature/%s", s.rt.Task.ID)
			beBranch := fmt.Sprintf("feature/%s-be", s.rt.Task.ID)
			feBranch := fmt.Sprintf("feature/%s-fe", s.rt.Task.ID)

			var ws *models.TaskWorkspace
			if s.workspace != nil {
				ws, _ = s.workspace.LoadTaskWorkspace(ctx, s.rt.Task)
			}
			s.worktree.SetupRoleBranches(ctx, s.rt.Task, s.rt.Agent, s.rt.JobID, targetRepos, ws, skipFE)
			branchesMap := map[string]string{
				"integration": integrationBranch,
				"backend":     beBranch,
			}
			if !skipFE {
				branchesMap["frontend"] = feBranch
			}
			out["branches"] = branchesMap
		}
	}

	if s.status != nil {
		if _, err := s.status.UpdateTaskStatus(ctx, s.rt.Task.ID, models.TaskStatusCoding); err != nil {
			return nil, err
		}
	}
	s.log.Log(ctx, s.rt.Task.ID, &s.rt.JobID, "info", "Plan: orchestration checkpoint complete")
	return out, nil
}

// parseTasksMD extracts structured subtasks from the tasks_md markdown generated
// by the Analyze step. It classifies each heading group as "backend" or "frontend"
// based on keyword matching, then collects checkbox items under each group.
//
// Input format (from OpenSpec):
//
//	## 1. Backend API
//	- [ ] 1.1 Create API endpoint
//	- [ ] 1.2 Add validation
//	## 2. Frontend Components
//	- [ ] 2.1 Build form component
//
// Output: map[string][]string{
//
//	"backend":  ["1.1 Create API endpoint", "1.2 Add validation"],
//	"frontend": ["2.1 Build form component"],
//
// }

// shouldSkipFrontend determines whether the frontend coding step should be skipped
// based on the task analysis and parsed subtask breakdown.
func shouldSkipFrontend(analysis models.TaskAnalysis, subtasks map[string][]string) bool {
	// 1. If any affected files are frontend files, do NOT skip (file-path signal overrides category hint)
	for _, file := range analysis.AffectedFiles {
		if isFrontendFile(file.File) {
			return false
		}
	}

	// 2. If frontend subtasks exist, keep the frontend step enabled even if the
	// category hint leans backend.
	if len(subtasks["frontend"]) > 0 {
		return false
	}

	// 3. Fallback: if category is backend/database/devops/security/documentation, skip
	switch strings.ToLower(analysis.PrimaryCategory) {
	case "backend", "database", "devops", "security", "documentation":
		return true
	}

	// 4. Default: no frontend file signal, no frontend subtasks, and no explicit
	// non-frontend category hint. Skip the frontend step.
	return true
}
