package models

import (
	"bytes"
	"context"
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
	"time"
)

type contextKey string

const StateMachineEnabledCtxKey contextKey = "state_machine_enabled"

func IsStateMachineEnabled(ctx context.Context) bool {
	enabled, _ := ctx.Value(StateMachineEnabledCtxKey).(bool)
	return enabled
}

//go:embed schemas/execution_ir.schema.json
var executionIRSchemaJSON []byte

// CurrentExecutionIRSchemaVersion is the schema_version this build accepts.
// A Planner emitting any other value fails validation rather than being
// parsed best-effort (see docs/openspecs/execution-semantics-2026).
const CurrentExecutionIRSchemaVersion = "1.0"

var validExecutionIROperations = map[string]bool{
	"create":   true,
	"modify":   true,
	"delete":   true,
	"refactor": true,
}

// Intent defines the semantic goal for an execution node.
type Intent struct {
	Capability string `json:"capability"`
	Operation  string `json:"operation"`
}

// PhaseBudgets allocates iteration counts for each state machine phase.
type PhaseBudgets struct {
	Discovery      int `json:"discovery"`
	Implementation int `json:"implementation"`
	Validation     int `json:"validation"`
}

// ExecutionIR is the rigid semantic execution contract generated by planners.
type ExecutionIR struct {
	SchemaVersion string       `json:"schema_version"`
	NodeID        string       `json:"node_id"`
	Intent        Intent       `json:"intent"`
	Constraints   []string     `json:"constraints"`
	Acceptance    []string     `json:"acceptance"`
	Budget        PhaseBudgets `json:"budget"`
}

// ExecutionIRSchema returns the strict JSON schema for ExecutionIR, parsed
// from the embedded schemas/execution_ir.schema.json (single source of truth
// shared with external tooling).
func ExecutionIRSchema() map[string]any {
	var schema map[string]any
	_ = json.Unmarshal(executionIRSchemaJSON, &schema)
	return schema
}

// ExecutionIRValidationErrors is a structured, field-level validation failure.
type ExecutionIRValidationErrors []string

func (e ExecutionIRValidationErrors) Error() string {
	return fmt.Sprintf("execution IR validation failed: %s", strings.Join(e, "; "))
}

// ValidateExecutionIR checks an already-decoded ExecutionIR against the
// contract's required-field and enum rules. Unknown-field rejection happens
// earlier, at decode time (see ParseExecutionIR).
func ValidateExecutionIR(ir ExecutionIR) error {
	var errs ExecutionIRValidationErrors

	if ir.SchemaVersion != CurrentExecutionIRSchemaVersion {
		errs = append(errs, fmt.Sprintf("schema_version: must be %q, got %q", CurrentExecutionIRSchemaVersion, ir.SchemaVersion))
	}
	if strings.TrimSpace(ir.NodeID) == "" {
		errs = append(errs, "node_id: required")
	}
	if strings.TrimSpace(ir.Intent.Capability) == "" {
		errs = append(errs, "intent.capability: required")
	}
	if !validExecutionIROperations[strings.ToLower(ir.Intent.Operation)] {
		errs = append(errs, fmt.Sprintf("intent.operation: must be one of create|modify|delete|refactor, got %q", ir.Intent.Operation))
	}
	if ir.Constraints == nil {
		errs = append(errs, "constraints: required (may be empty array)")
	}
	if ir.Acceptance == nil {
		errs = append(errs, "acceptance: required (may be empty array)")
	}
	if ir.Budget.Discovery < 0 || ir.Budget.Implementation < 0 || ir.Budget.Validation < 0 {
		errs = append(errs, "budget: values must be non-negative")
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

// ParseExecutionIR decodes raw Planner output into an ExecutionIR, rejecting
// unknown fields (additionalProperties: false) and running ValidateExecutionIR
// before the value is ever handed to a PromptCompiler (REQ-001).
func ParseExecutionIR(data []byte) (ExecutionIR, error) {
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()

	var ir ExecutionIR
	if err := dec.Decode(&ir); err != nil {
		return ExecutionIR{}, fmt.Errorf("execution IR decode: %w", err)
	}
	if err := ValidateExecutionIR(ir); err != nil {
		return ExecutionIR{}, err
	}
	return ir, nil
}

type ExecutionSnapshot struct {
	ExecutionID   string           `json:"execution_id"`
	CurrentState  string           `json:"current_state"`  // one of the state machine states
	Iteration     int              `json:"iteration"`      // within CurrentState
	WorkspaceDiff string           `json:"workspace_diff"` // unified diff vs. node entry workspace
	ToolHistory   []ToolCallRecord `json:"tool_history"`
	PromptHash    string           `json:"prompt_hash"` // hash of compiled prompt for replay integrity
	SemanticHash  string           `json:"semantic_hash"`
	Timestamp     time.Time        `json:"timestamp"`
}

type ToolCallRecord struct {
	State     string          `json:"state"`
	Iteration int             `json:"iteration"`
	Tool      string          `json:"tool"`
	Args      json.RawMessage `json:"args"`
	Result    string          `json:"result"` // truncated per config
	Error     string          `json:"error,omitempty"`
}

func ComputeSemanticHash(ir ExecutionIR, resolvedTargets []string) string {
	h := sha256.New()
	fmt.Fprintf(h, "node=%s\nop=%s\ncap=%s\n", ir.NodeID, ir.Intent.Operation, ir.Intent.Capability)

	sortedTargets := append([]string(nil), resolvedTargets...)
	sort.Strings(sortedTargets)
	for _, t := range sortedTargets {
		fmt.Fprintf(h, "target=%s\n", t)
	}

	sortedAcceptance := append([]string(nil), ir.Acceptance...)
	sort.Strings(sortedAcceptance)
	for _, a := range sortedAcceptance {
		fmt.Fprintf(h, "acceptance=%s\n", a)
	}

	sortedConstraints := append([]string(nil), ir.Constraints...)
	sort.Strings(sortedConstraints)
	for _, c := range sortedConstraints {
		fmt.Fprintf(h, "constraint=%s\n", c)
	}
	return hex.EncodeToString(h.Sum(nil))
}
