package orchestrator

import (
	"context"
	"fmt"
	"log/slog"
	"strings"

	"github.com/auto-code-os/auto-code-os/server/pkg/models"
)

// PRGenerator builds AI-generated PR summaries and risk assessments.
type PRGenerator struct{}

func NewPRGenerator() *PRGenerator {
	return &PRGenerator{}
}

type FileDiff struct {
	Name    string
	Added   int
	Deleted int
}

func parseDiff(diffText string) []FileDiff {
	lines := strings.Split(diffText, "\n")
	var result []FileDiff
	var current *FileDiff

	for _, line := range lines {
		if strings.HasPrefix(line, "diff --git ") {
			parts := strings.Fields(line)
			if len(parts) >= 3 {
				name := parts[2]
				if strings.HasPrefix(name, "a/") {
					name = name[2:]
				}
				result = append(result, FileDiff{Name: name})
				current = &result[len(result)-1]
			}
		} else if current != nil {
			if strings.HasPrefix(line, "+") && !strings.HasPrefix(line, "+++") {
				current.Added++
			} else if strings.HasPrefix(line, "-") && !strings.HasPrefix(line, "---") {
				current.Deleted++
			}
		}
	}
	return result
}

// GenerateSummary creates a structured PR summary from task data, agent info, changed files, git diff, and test results.
func (g *PRGenerator) GenerateSummary(
	ctx context.Context,
	task *models.Task,
	agent *models.Agent,
	changedFiles []string,
	diffText string,
	testResult map[string]any,
) *models.PRSummary {
	title := fmt.Sprintf("AutoCodeOS: %s", task.Title)

	// Build the PR body using the spec template.
	var body strings.Builder
	body.WriteString(fmt.Sprintf("## AutoCodeOS: %s\n\n", task.Title))
	body.WriteString(fmt.Sprintf("**Task:** #%s\n", task.ID))

	agentRole := "Unknown Agent"
	modelLevel := "unknown"
	if agent != nil {
		agentRole = agent.Role
		modelLevel = agent.ModelLevelGroup
	}
	body.WriteString(fmt.Sprintf("**Agent:** %s (%s)\n", agentRole, modelLevel))
	body.WriteString(fmt.Sprintf("**Complexity:** %s\n\n", task.Complexity))

	body.WriteString("### Summary\n")
	if task.Description != "" {
		body.WriteString(fmt.Sprintf("%s\n\n", task.Description))
	} else {
		body.WriteString("Automated changes implemented by Auto Code OS.\n\n")
	}

	body.WriteString("### Changes\n")
	fileDiffs := parseDiff(diffText)
	if len(fileDiffs) > 0 {
		body.WriteString("| File | Action | Lines Changed |\n")
		body.WriteString("|------|--------|---------------|\n")
		for _, fd := range fileDiffs {
			action := "Modified"
			if fd.Added > 0 && fd.Deleted == 0 {
				action = "Added"
			} else if fd.Deleted > 0 && fd.Added == 0 {
				action = "Deleted"
			}
			body.WriteString(fmt.Sprintf("| %s | %s | +%d / -%d |\n", fd.Name, action, fd.Added, fd.Deleted))
		}
	} else {
		// Fallback if diffText is not provided
		body.WriteString("| File | Action | Lines Changed |\n")
		body.WriteString("|------|--------|---------------|\n")
		for _, f := range changedFiles {
			body.WriteString(fmt.Sprintf("| %s | Modified | +/- |\n", f))
		}
	}
	body.WriteString("\n")

	// Risk assessment based on task complexity and file count.
	riskLevel, riskReason := assessRisk(task, changedFiles)
	body.WriteString("### Risk Assessment\n")
	body.WriteString(fmt.Sprintf("- **Level:** %s\n", riskLevel))
	body.WriteString(fmt.Sprintf("- **Reason:** %s\n\n", riskReason))

	// Test Results
	body.WriteString("### Test Results\n")
	if testResult != nil {
		passed, _ := testResult["passed"].(bool)
		exitCode, _ := testResult["exit_code"].(float64)
		if passed {
			body.WriteString("- ✅ Unit tests: passed\n")
		} else {
			body.WriteString(fmt.Sprintf("- ❌ Unit tests: failed (exit code: %v)\n", exitCode))
		}
		if lintPassed, ok := testResult["lint_passed"].(bool); ok && lintPassed {
			body.WriteString("- ✅ Lint: passed\n")
		} else {
			body.WriteString("- ⚠️ Lint: Not executed\n")
		}
	} else {
		body.WriteString("- ⚠️ Unit tests: Not executed\n")
		body.WriteString("- ⚠️ Lint: Not executed\n")
	}
	body.WriteString("\n---\n")
	body.WriteString("*This PR was generated by Auto Code OS.*\n")

	slog.Info("pr summary generated", "task_id", task.ID, "files", len(changedFiles), "risk", riskLevel)

	return &models.PRSummary{
		Title:        title,
		Body:         body.String(),
		ChangedFiles: changedFiles,
		RiskLevel:    riskLevel,
		RiskReason:   riskReason,
		Status:       models.PRStatusOpen,
	}
}

// assessRisk evaluates the risk level of a PR based on task complexity and scope.
func assessRisk(task *models.Task, changedFiles []string) (string, string) {
	fileCount := len(changedFiles)

	// Check for critical file patterns.
	hasMigration := false
	hasConfig := false
	for _, f := range changedFiles {
		if strings.Contains(f, "migration/") {
			hasMigration = true
		}
		if strings.Contains(f, "config") || strings.Contains(f, ".env") || strings.Contains(f, "docker") {
			hasConfig = true
		}
	}

	switch {
	case hasMigration && task.Complexity == models.TaskComplexityHard:
		return models.PRRiskCritical, "Database migration in a hard-complexity task requires careful review"
	case hasMigration:
		return models.PRRiskHigh, "Contains database migration files"
	case task.Complexity == models.TaskComplexityHard || fileCount > 15:
		return models.PRRiskHigh, fmt.Sprintf("Hard complexity task affecting %d files", fileCount)
	case hasConfig:
		return models.PRRiskMedium, "Modifies configuration or infrastructure files"
	case task.Complexity == models.TaskComplexityMedium || fileCount > 5:
		return models.PRRiskMedium, fmt.Sprintf("Medium complexity task affecting %d files", fileCount)
	default:
		return models.PRRiskLow, fmt.Sprintf("Simple change affecting %d files", fileCount)
	}
}
